<p>
	<a href="<?php echo $this->url(
    array(
        'controller' => 'guestbook',
        'action'     => 'sign'
    ),
    'default',
    true) ?>">Im Guestbook eintragen</a>
</p>

<p>
	<a href="<?php echo $this->url(
    array(
        'controller' => 'guestbook',
        'action'     => 'clear'
    ),
    'default',
    true) ?>">Guestbook l&ouml;schen</a>
</p>

Guestbook Einträge: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->email) ?></dt>
    <dd><?php echo $this->escape($entry->comment) ?></dd>
    <?php endforeach ?>
</dl>
